// Generated by CoffeeScript 1.6.3
(function() {
  var handle, requestHandlers, router, server;

  server = require("./rabbitServer.js.coffee");

  router = require("./router.js.coffee");

  requestHandlers = require("./requestHandlers.js.coffee");

  handle = {};

  handle[addTarget] = requestHandlers.addTarget;

  handle[removeTarget] = requestHandlers.removeTarget;

  server.start(router.route, handle);

}).call(this);
